name: Gladiola Black Magic
description: Blog to accompany <a href="https://github.com/gladiola/blackmagic">gladiola/blackmagic repo</a>
meta_description: "Web development blog to accompany gladiola/blackmagic repo"

aboutPage: true

markdown: kramdown
highlighter: rouge

plugins: [jekyll-paginate]
paginate: 20
domain_name: 'https://gladiola.github.io/blog/'
google_analytics: 'UA-122871767-1'
disqus: false
disqus_shortname: 'https-github-com-gladiola-blog'

# Details for the RSS feed generator
url:            'https://gladiola.github.io/blog/'
author:         'Gladiola'
authorTwitter:  'AgXphoto'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
